/// Firebase configuration — generated by FlutterFire CLI.
///
/// Run `flutterfire configure` after creating your Firebase project to
/// regenerate this file with your project's actual credentials.
///
/// Steps:
/// 1. Go to https://console.firebase.google.com and create a project named "apnasolar"
/// 2. Install Firebase CLI: npm install -g firebase-tools
/// 3. firebase login
/// 4. dart pub global activate flutterfire_cli
/// 5. flutterfire configure --project=`your-project-id`
///
/// PLACEHOLDER — replace with actual FlutterFire-generated file before building.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// PLACEHOLDER — replace with your Firebase project's actual values.
  /// Run `flutterfire configure` to generate the correct values.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62zpfhxJ6yUwCSqF2hQTfPtoBs3AtnEw',
    appId: '1:826262863047:web:aca1c7593b2c48a61f12e2',
    messagingSenderId: '826262863047',
    projectId: 'apnasolar-ace80',
    authDomain: 'apnasolar-ace80.firebaseapp.com',
    storageBucket: 'apnasolar-ace80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6g0Tn5z-0Q4zS040JLelOWYNZQmA4Uok',
    appId: '1:826262863047:android:17bec3e9b7442e251f12e2',
    messagingSenderId: '826262863047',
    projectId: 'apnasolar-ace80',
    storageBucket: 'apnasolar-ace80.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOucoUPpUnoWCeSAkMgB9wgaKwczPYBo',
    appId: '1:826262863047:ios:eb93b001aedb771e1f12e2',
    messagingSenderId: '826262863047',
    projectId: 'apnasolar-ace80',
    storageBucket: 'apnasolar-ace80.firebasestorage.app',
    iosBundleId: 'com.apnasolar.apnasolar',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOucoUPpUnoWCeSAkMgB9wgaKwczPYBo',
    appId: '1:826262863047:ios:eb93b001aedb771e1f12e2',
    messagingSenderId: '826262863047',
    projectId: 'apnasolar-ace80',
    storageBucket: 'apnasolar-ace80.firebasestorage.app',
    iosBundleId: 'com.apnasolar.apnasolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62zpfhxJ6yUwCSqF2hQTfPtoBs3AtnEw',
    appId: '1:826262863047:web:4b4c17bdefcffb4a1f12e2',
    messagingSenderId: '826262863047',
    projectId: 'apnasolar-ace80',
    authDomain: 'apnasolar-ace80.firebaseapp.com',
    storageBucket: 'apnasolar-ace80.firebasestorage.app',
  );
}
